// paymentController.js — Razorpay payment integration
//
// FLOW:
// 1. Frontend calls POST /api/payments/create-order  → we create a Razorpay order, return order_id
// 2. Frontend opens Razorpay popup with order_id
// 3. User pays → Razorpay returns { razorpay_payment_id, razorpay_order_id, razorpay_signature }
// 4. Frontend calls POST /api/payments/verify → we verify the signature on the backend
// 5. If valid → mark booking as PAID in DB → return success
//
// WHY verify on backend?
// Anyone can fake a payment_id on the frontend. The HMAC signature can only be
// generated by Razorpay using your secret key — so verifying it server-side
// proves the payment is genuine.

const Razorpay  = require('razorpay');
const crypto    = require('crypto');   // built into Node.js — no install needed
const db        = require('../config/database');
const { sendSuccess, sendError } = require('../utils/response');

// Create Razorpay instance only if keys are available
let razorpay = null;
if (process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET) {
  razorpay = new Razorpay({
    key_id:     process.env.RAZORPAY_KEY_ID,
    key_secret: process.env.RAZORPAY_KEY_SECRET,
  });
}

// ─────────────────────────────────────────────────────────
// POST /api/payments/create-order
// Creates a Razorpay order for a given booking
// Returns: { order_id, amount, currency, key_id }
// ─────────────────────────────────────────────────────────
const createOrder = async (req, res) => {
  try {
    const { booking_id } = req.body;

    // Fetch booking from DB — we get the real amount, never trust the frontend
    const [bookings] = await db.query(
      'SELECT id, booking_reference, total_amount, payment_status, user_id FROM bookings WHERE id = ?',
      [booking_id]
    );

    if (bookings.length === 0) {
      return sendError(res, 'Booking not found', 404);
    }

    const booking = bookings[0];

    // Only the booking owner can pay
    if (booking.user_id !== req.user.userId) {
      return sendError(res, 'Access denied', 403);
    }

    // Don't create a new order if already paid
    if (booking.payment_status === 'PAID') {
      return sendError(res, 'This booking is already paid', 400);
    }

    // Razorpay amount is in PAISE (1 rupee = 100 paise)
    const amountInPaise = Math.round(parseFloat(booking.total_amount) * 100);

    // Create a Razorpay order
    // This locks the amount — the user cannot change it in the popup
    const order = await razorpay.orders.create({
      amount:   amountInPaise,
      currency: 'INR',
      receipt:  booking.booking_reference,  // shows in Razorpay dashboard
      notes: {
        booking_id:        String(booking.id),
        booking_reference: booking.booking_reference,
      },
    });

    // Save the order_id in our DB so we can verify later
    await db.query(
      'UPDATE bookings SET razorpay_order_id = ? WHERE id = ?',
      [order.id, booking.id]
    );

    // Return order details + the key_id (public, safe to send to frontend)
    return sendSuccess(res, {
      order_id:          order.id,
      amount:            order.amount,       // in paise
      amount_display:    booking.total_amount, // in rupees (for display)
      currency:          order.currency,
      booking_reference: booking.booking_reference,
      key_id:            process.env.RAZORPAY_KEY_ID,  // public key, safe to send
    }, 'Order created successfully');

  } catch (error) {
    console.error('createOrder error:', error);
    // Don't leak Razorpay internals — generic message
    return sendError(res, 'Failed to create payment order. Please try again.', 500);
  }
};

// ─────────────────────────────────────────────────────────
// POST /api/payments/verify
// Verifies the payment signature from Razorpay
// This is the CRITICAL security step
// ─────────────────────────────────────────────────────────
const verifyPayment = async (req, res) => {
  try {
    const {
      razorpay_order_id,
      razorpay_payment_id,
      razorpay_signature,
      booking_id,
    } = req.body;

    // Fetch booking
    const [bookings] = await db.query(
      'SELECT id, user_id, razorpay_order_id, payment_status FROM bookings WHERE id = ?',
      [booking_id]
    );

    if (bookings.length === 0) return sendError(res, 'Booking not found', 404);
    const booking = bookings[0];

    if (booking.user_id !== req.user.userId) return sendError(res, 'Access denied', 403);
    if (booking.payment_status === 'PAID') return sendError(res, 'Already paid', 400);

    // ── SIGNATURE VERIFICATION ──
    // Razorpay creates a signature by hashing (order_id + "|" + payment_id) with your secret key
    // We recreate the same hash and compare — if they match, the payment is genuine
    const body           = razorpay_order_id + '|' + razorpay_payment_id;
    const expectedSignature = crypto
      .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
      .update(body)
      .digest('hex');

    if (expectedSignature !== razorpay_signature) {
      // Signature mismatch = payment was tampered with or fake
      console.warn('⚠️  Payment signature mismatch for booking:', booking_id);
      await db.query(
        "UPDATE bookings SET payment_status = 'FAILED' WHERE id = ?",
        [booking_id]
      );
      return sendError(res, 'Payment verification failed. Please contact support.', 400);
    }

    // ── PAYMENT IS GENUINE — update DB ──
    await db.query(`
      UPDATE bookings SET
        payment_status       = 'PAID',
        booking_status       = 'CONFIRMED',
        razorpay_payment_id  = ?,
        razorpay_signature   = ?,
        paid_at              = NOW()
      WHERE id = ?
    `, [razorpay_payment_id, razorpay_signature, booking_id]);

    // Fetch updated booking to return
    const [updated] = await db.query(`
      SELECT b.*, v.name AS vehicle_name
      FROM bookings b
      JOIN vehicles v ON b.vehicle_id = v.id
      WHERE b.id = ?
    `, [booking_id]);

    return sendSuccess(res, {
      booking: updated[0],
      payment_id: razorpay_payment_id,
    }, '🎉 Payment successful! Your booking is confirmed.');

  } catch (error) {
    console.error('verifyPayment error:', error);
    return sendError(res, 'Payment verification failed. Please contact support.', 500);
  }
};

// ─────────────────────────────────────────────────────────
// POST /api/payments/webhook
// Razorpay calls this URL automatically when a payment event happens
// Useful for catching payments that complete after the user closes the browser
// ─────────────────────────────────────────────────────────
const handleWebhook = async (req, res) => {
  try {
    const webhookSecret   = process.env.RAZORPAY_WEBHOOK_SECRET;
    const webhookSignature = req.headers['x-razorpay-signature'];

    // Verify webhook signature (same HMAC approach)
    if (webhookSecret && webhookSignature) {
      const expectedSig = crypto
        .createHmac('sha256', webhookSecret)
        .update(JSON.stringify(req.body))
        .digest('hex');

      if (expectedSig !== webhookSignature) {
        return res.status(400).json({ error: 'Invalid webhook signature' });
      }
    }

    const event = req.body;

    // Handle payment.captured event
    if (event.event === 'payment.captured') {
      const payment  = event.payload.payment.entity;
      const orderId  = payment.order_id;

      await db.query(`
        UPDATE bookings SET
          payment_status      = 'PAID',
          booking_status      = 'CONFIRMED',
          razorpay_payment_id = ?,
          paid_at             = NOW()
        WHERE razorpay_order_id = ? AND payment_status != 'PAID'
      `, [payment.id, orderId]);

      console.log('✅ Webhook: Payment captured for order', orderId);
    }

    // Handle payment.failed event
    if (event.event === 'payment.failed') {
      const payment = event.payload.payment.entity;
      await db.query(
        "UPDATE bookings SET payment_status = 'FAILED' WHERE razorpay_order_id = ?",
        [payment.order_id]
      );
    }

    // Always return 200 to tell Razorpay we received it
    return res.status(200).json({ status: 'ok' });

  } catch (error) {
    console.error('webhook error:', error);
    return res.status(500).json({ error: 'Webhook processing failed' });
  }
};

// ─────────────────────────────────────────────────────────
// GET /api/payments/booking/:id
// Returns payment status of a booking
// ─────────────────────────────────────────────────────────
const getPaymentStatus = async (req, res) => {
  try {
    const [rows] = await db.query(
      `SELECT id, booking_reference, total_amount, payment_status, booking_status,
              razorpay_order_id, razorpay_payment_id, paid_at
       FROM bookings WHERE id = ? AND user_id = ?`,
      [req.params.id, req.user.userId]
    );

    if (rows.length === 0) return sendError(res, 'Booking not found', 404);
    return sendSuccess(res, rows[0], 'Payment status retrieved');

  } catch (error) {
    return sendError(res, 'Failed to get payment status', 500);
  }
};

module.exports = { createOrder, verifyPayment, handleWebhook, getPaymentStatus };
